# Generated by Django 5.1.1 on 2024-12-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='concert_images/')),
                ('hall_map', models.ImageField(upload_to='hall_maps/')),
            ],
        ),
    ]
