# Generated by Django 5.1.1 on 2025-01-09 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='concerts.seat')),
            ],
        ),
    ]
