# Generated by Django 5.1.1 on 2025-01-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0003_concert_price_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=8),
        ),
    ]
