# Generated by Django 5.1.1 on 2025-01-12 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0005_remove_booking_user_email_remove_booking_user_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='hall_map',
        ),
        migrations.RemoveField(
            model_name='concert',
            name='price',
        ),
        migrations.AddField(
            model_name='seat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concert_images/'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('concert', 'row', 'seat_number')},
        ),
    ]
