# Generated by Django 5.1.1 on 2025-01-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0006_remove_concert_hall_map_remove_concert_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='concert',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(upload_to='concert_images/'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
